root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
plugins:
  - react
  - "@typescript-eslint"
  - filenames
  - tsc
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - next
  - next/core-web-vitals
  - prettier
rules:
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/consistent-type-imports": "error"
  "@typescript-eslint/no-floating-promises":
    - "error"
    - ignoreVoid: true
  "@typescript-eslint/no-unused-vars":
    - "error"
    - varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
  "@next/next/no-img-element": "off"
  import/no-anonymous-default-export: "off"
  react/display-name: "off"
  react/react-in-jsx-scope: "off"
  filenames/match-exported: error
  tsc/config: [error, { configFile: "tsconfig.json" }]
overrides:
  - files:
      - jest.config.js
      - next.config.js
    env:
      node: true
    rules:
      "@typescript-eslint/no-var-requires": "off"
  - files:
      - samples/**
    rules:
      no-irregular-whitespace: "off"
  - files: pages/**
    rules:
      filenames/match-exported: "off"
  - files: [types/**, server/types/**]
    rules:
      filenames/match-exported: [error, camel]
  - files: [types/defaultTheme.d.ts]
    rules:
      "@typescript-eslint/no-empty-interface": "off"
