root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.eslint.json
plugins:
  - react
  - "@typescript-eslint"
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jsx-a11y/recommended
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - prettier
  - prettier/@typescript-eslint
rules:
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-unused-vars": "error"
  react/react-in-jsx-scope: "off"
overrides:
  - files:
      - next.config.js
    env:
      node: true
  - files:
      - samples/**
    rules:
      no-irregular-whitespace: "off"
