# NOTE: DON'T USE IT IN PRODUCTION. 本番環境で使用しないで。
version: "3"
services:
  mariadb:
    image: "mariadb:10.8.3-jammy"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bitnami_moodle
    # volumes:
    #   - ./db.sql:/docker-entrypoint-initdb.d/db.sql # NOTE: SQLファイルによる投入例
  moodle:
    image: "bitnami/moodle:4.0.2-debian-11-r7"
    ports: ["8081:8080"]
    environment:
      MOODLE_USERNAME: user
      MOODLE_PASSWORD: password
      ALLOW_EMPTY_PASSWORD: "yes"
      MOODLE_DATABASE_USER: root
      BITNAMI_DEBUG: "true"
    depends_on: [mariadb]
  db:
    image: "postgres:14.4-alpine3.16"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
  app:
    image: "node:16.16-alpine3.16"
    environment:
      FRONTEND_ORIGIN: "http://localhost:3000"
      SESSION_SECRET: super_secret_characters_for_session
      OAUTH_CONSUMER_KEY: test
      OAUTH_CONSUMER_SECRET: test
      DATABASE_URL: postgresql://postgres:password@db/postgres
    user: ${UID:-1000}:${GID:-1000}
    command: "sh -c 'cd /app && yarn && yarn dev'"
    volumes: ["./:/app"]
    ports:
      - "3000:3000"
      - "5555:5555"
      - "8080:8080"
    depends_on: [moodle, db]
