ignorePatterns:
  - "/dist"
overrides:
  - files: "jest.config.js"
    env: { node: true }
    rules:
      "@typescript-eslint/no-var-requires": "off"
  - files: "utils/handler.ts"
    rules:
      "@typescript-eslint/no-explicit-any": off
