name: build
on: pull_request
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: yarn
      - name: install
        run: yarn
      - name: lint
        run: yarn lint:fix:report
        continue-on-error: true
      - name: "commit lint:fix"
        run: |
          if git -c "user.name=bot" -c "user.email=bot@example" commit -am "bot: lint:fix"; then
            git push origin HEAD
          fi
      - uses: ataylorme/eslint-annotate-action@v2
        with: { repo-token: "${{ github.token }}" }
      - name: format
        run: yarn format
      - name: "commit format"
        run: |
          if git -c "user.name=bot" -c "user.email=bot@example" commit -am "bot: format"; then
            git push origin HEAD
          fi
      - name: test
        run: yarn test
      - name: build
        run: yarn build
